version: '3.5'

services:
    app:
        build:
            context: .
            dockerfile: docker/production/Dockerfile
        volumes:
            - .:/code
        ports:
            - 8000:8000
        env_file: 
            - conf/.env
        command: /start
    geo:
        image: registry.gitlab.com/coderio/backend/geoinversa
        depends_on:
            - app
        ports:
            - 3000:3000
        env_file: 
            - conf/.env

