version: '3.5'
volumes:
    production_traefik: {}
services:
    app:
        build:
            context: .
            dockerfile: docker/production/Dockerfile
        volumes:
            - .:/code
        env_file: 
            - conf/.env
        command: /start
    geo:
        image: registry.gitlab.com/coderio/backend/geoinversa
        depends_on:
            - app
        env_file: 
            - conf/.env
    traefik:
        build:
            context: .
            dockerfile: ./docker/production/traefik/Dockerfile
        image: argxvos_production_traefik
        depends_on:
            - app
        volumes:
            - production_traefik:/etc/traefik/acme
        ports:
            - "0.0.0.0:80:80"
            - "0.0.0.0:443:443"
            - "0.0.0.0:3000:3000"

