version: '3.5'

services:
    app:
        build:
            context: .
            dockerfile: docker/production/Dockerfile
        volumes:
            - .:/code
        ports:
            - 8000:8000
        env_file: 
            - conf/.env
        command: /start

