version: '3.5'
services:
    app:
        build:
            context: .
            dockerfile: docker/production/Dockerfile
        volumes:
            - .:/code
        env_file: 
            - conf/.env
        command: /start
        ports:
            - "8000:8000"
        labels:
            - "traefik.http.routers.staging.rule=Host(`staging.argentinaporvos.org`)"
