version: '3.5'
services:
    staging_app:
        build:
            context: .
            dockerfile: docker/production/Dockerfile
        volumes:
            - .:/code
        env_file: 
            - conf/.env
        command: /start_stg
        ports:
            - "5000:5000"
