# Generated by Django 2.0 on 2020-04-24 16:41

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_helprequest_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='picture',
            field=models.ImageField(blank=True, help_text='<p class="help text-muted has-text-left" style="margin:0 0 5px 5px;">Si querés podés adjuntar una foto relacionada con tu pedido, es opcional pero puede ayudar a que la gente entienda mejor tu situación</p>', null=True, upload_to=core.utils.rename_img, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='picture',
            field=models.TextField(blank=True, help_text='<p class="help text-muted has-text-left" style="margin:0 0 5px 5px;">Si querés podés adjuntar una foto relacionada con tu pedido, es opcional pero puede ayudar a que la gente entienda mejor tu situación</p>', max_length=100, null=True, verbose_name='Foto'),
        ),
    ]
