# Generated by Django 2.0 on 2020-05-26 16:36

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200424_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='address',
            field=models.CharField(help_text='Puede ser la de tu casa, como la de un lugar público cerca de la misma (comisaría, hospital, kiosko, plaza, estación de servicio).', max_length=400, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='message',
            field=models.TextField(db_index=True, help_text='Acá podés contar detalladamente lo que necesitás, <b>cuanto mejor cuentes tu situación es más probable que te quieran ayudar.</b>', max_length=2000, null=True, verbose_name='Descripción del pedido'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='picture',
            field=models.ImageField(blank=True, help_text='<p class="help text-muted has-text-left" style="margin:0 0 5px 5px;">Si querés podés adjuntar una foto relacionada con tu pedido, es opcional pero puede ayudar a que la gente entienda mejor tu situación.</p>', null=True, upload_to=core.utils.rename_img, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='title',
            field=models.CharField(db_index=True, help_text='Descripción corta de qué estás necesitando.', max_length=200, verbose_name='Título del pedido'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='address',
            field=models.CharField(help_text='Puede ser la de tu casa, como la de un lugar público cerca de la misma (comisaría, hospital, kiosko, plaza, estación de servicio).', max_length=400, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='message',
            field=models.TextField(db_index=True, help_text='Acá podés contar detalladamente lo que necesitás, <b>cuanto mejor cuentes tu situación es más probable que te quieran ayudar.</b>', max_length=2000, null=True, verbose_name='Descripción del pedido'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='picture',
            field=models.TextField(blank=True, help_text='<p class="help text-muted has-text-left" style="margin:0 0 5px 5px;">Si querés podés adjuntar una foto relacionada con tu pedido, es opcional pero puede ayudar a que la gente entienda mejor tu situación.</p>', max_length=100, null=True, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='title',
            field=models.CharField(db_index=True, help_text='Descripción corta de qué estás necesitando.', max_length=200, verbose_name='Título del pedido'),
        ),
    ]
