name: CI
on:
  push:
    branches: [ staging ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        uses: fifsky/ssh-action@master
        with:
          command: |
            ./deploy_stg.sh
          host: ${{ secrets.HOST_PROD }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY}}
